import { PlusIcon } from "lucide-react"
import { Accordion as AccordionPrimitive } from "radix-ui"

import {
  Accordion,
  AccordionContent,
  AccordionItem,
} from "@/components/ui/accordion"

const items = [
  {
    id: "1",
    title: "Connected accounts",
    sub: "How Medical Teams and Patients Stay in Sync",
    content:
      "Medical member share their code that is generated by the app to connect with patients. This allows for seamless communication and coordination of care. Patients can view their medical team's schedule, upcoming appointments, and any notes or updates shared by their healthcare providers.",
  },
  {
    id: "2",
    title: "Notifications",
    sub: "Customize your notification preferences as a patient",
    content:
      "Choose which notifications you want to receive, such as medication reminders, appointment updates, and health tips. You can also set your preferred notification channels, whether it's via email, SMS, or in-app notifications. This ensures you stay informed about your health without being overwhelmed by unnecessary alerts.",
  },
  {
    id: "3",
    title: "Medical Staff Code",
    sub: "What is the Medical Staff Code?",
    content:
      "The Medical Staff Code is a unique identifier generated by the app for healthcare professionals. It allows patients to connect with their medical team securely. By entering this code, patients can access their healthcare provider's schedule, view upcoming appointments, and receive important updates related to their care. This feature enhances communication and ensures that patients are always informed about their health management.",
  },
  {
    id: "4",
    title: "Contact support",
    sub: "We're here to help 24/7",
    content:
      "Our support team is available around the Clock to assist you. For technical issues, or general questions, you can reach us through live chat, email at MedReminder@gmail.com, or schedule a call with our technical team. Premium support is available for all.",
  },
]

export default function AskedQuestions() {
  return (
    <div className="space-y-4">
      <h2 className="text-xl text-center font-bold">Frequently asked questions</h2>
      <h3 className="text-center">Everything you need to know about the App</h3>
      <Accordion type="single" collapsible className="w-3/4 h-auto mx-auto content-center" defaultValue="3">
        {items.map((item) => (
          <AccordionItem value={item.id} key={item.id} className="py-2">
            <AccordionPrimitive.Header className="flex">
              <AccordionPrimitive.Trigger className="focus-visible:border-ring focus-visible:ring-ring/50 flex flex-1 items-center justify-between rounded-md py-2 text-left text-[15px] leading-6 font-semibold transition-all outline-none focus-visible:ring-[3px] [&>svg>path:last-child]:origin-center [&>svg>path:last-child]:transition-all [&>svg>path:last-child]:duration-200 [&[data-state=open]>svg]:rotate-180 [&[data-state=open]>svg>path:last-child]:rotate-90 [&[data-state=open]>svg>path:last-child]:opacity-0">
                <span className="flex flex-col space-y-1">
                  <span>{item.title}</span>
                  {item.sub && (
                    <span className="text-sm font-normal">{item.sub}</span>
                  )}
                </span>
                <PlusIcon
                  size={16}
                  className="pointer-events-none shrink-0 opacity-60 transition-transform duration-200"
                  aria-hidden="true"
                />
              </AccordionPrimitive.Trigger>
            </AccordionPrimitive.Header>
            <AccordionContent className="text-muted-foreground pb-2">
              {item.content}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  )
}
